spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username:
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true  # 이 설정을 추가해주세요
  sql:
    init:
      mode: always



#spring:
#  datasource:
#    url: jdbc:mysql://database-1.c3wegsguqjcy.ap-northeast-2.rds.amazonaws.com:3306/farm_info?serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: kwon
#    password: yh990523
#  jpa:
#    hibernate:
#      ddl-auto: update  # create에서 update로 변경 (데이터 유지)
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect