spring:
  datasource:
    url: jdbc:mysql://database-1.c3wegsguqjcy.ap-northeast-2.rds.amazonaws.com:3306/farm_info?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kwon
    password: yh990523
  jpa:
    hibernate:
      ddl-auto: create  # 서버 시작시 테이블 생성, 종료시 삭제
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always